### Example
GET http://rpi1:8000/devices HTTP/1.1
Authorization: Basic ale figueroa

### Example
GET http://rpi1:8000/devices/f1989d25-c311-44c2-85ab-6eb6c48ebfef HTTP/1.1
Authorization: Basic ale figueroa

### Create
POST http://rpi1:8000/devices HTTP/1.1
Authorization: Basic ale figueroa
content-type: application/json

{
    "name": "Andi",
    "mac": "11:11:11:11:11:ab",
    "ssid": "FakeSSID",
    "enabled": true
}
### Update
PUT http://rpi1:8000/devices/f1989d25-c311-44c2-85ab-6eb6c48ebfef HTTP/1.1
Authorization: Basic ale figueroa
content-type: application/json

{
    "enabled": false 
}
###
POST http://rpi1:8000/devices HTTP/1.1
Authorization: Basic ale figueroa
content-type: application/json

{
    "name": "TarolasH2",
    "mac": "11:11:11:11:11:ab",
    "ssid": "tarolas-h2",
    "enabled": true
}